### PR TITLE
#13 binary for Apple M1

### PR DESCRIPTION
**Pull request by IstvanOri**
First steps:
 - Makefiles for Macos are added for the RInChI library and for the command line tool
 - README and BUILD.TXT files are updated

Only local compilation is available right now.

TODO: Notarization

### CODE REVIEW

**Comment by IstvanOri** [comment]
There are altered qt.pro files. I have added some compiler version related entries. These entries are not a must to move forward with the issue, but seem to be useful, because the compiler version is very important due the underlying InChI project.

**Comment by janholstjensen** [comment]
Thanks Istvan! Do you generate the Mac makefiles directly from the qt project files ?

I am thinking about the changes that will happen when we switch to the latest InChI version; these will affect the qt project files quite a bit. Wondering how much manual work will need to be done to maintain the Mac makefiles whenever the qt projects change.

**Comment by IstvanOri** [comment]
Sorry for the late reply, it seems  that I have to update my notification settings.

The Makefile was generated from the qt projectfile, but in some cases the Makefile needs some patches, such as removal of some misbihaving options (i.e. minimum mac version). I altered the qt project file as well to minimalize the required manual changes on the Makefile.

**Comment by janholstjensen** [comment]
Closing and discarding this pull request with thanks, since we have found a simpler way to generate makefiles that work on Mac.

**Pull request closed without merging**
